use once_cell::sync::Lazy;
use std::collections::HashSet;

pub static CEDH_STAPLES: Lazy<HashSet<String>> = Lazy::new(|| {
    [
        "Thassa's Oracle",
        "Demonic Consultation",
        "Tainted Pact",
        "Underworld Breach",
        "Ad Nauseam",
        "Dockside Extortionist",
        "Brain Freeze",
        "Lion's Eye Diamond",
        "Intuition",
        "Grinding Station",
        "Isochron Scepter",
        "Dramatic Reversal",
        "Finale of Devastation",
        "Birthing Pod",
        "Necropotence",
        "Peer into the Abyss",
        "Yawgmoth's Will",
        "Sevinne's Reclamation",
        "Wishclaw Talisman",
        "Force of Will",
        "Fierce Guardianship",
        "Force of Negation",
        "Pact of Negation",
        "Flusterstorm",
        "Deflecting Swat",
        "Walking Ballista",
        "Necrodominance",
        "Mental Misstep",
        "Mox Diamond",
        "Grim Monolith",
        "Chrome Mox",
        "Timetwister",
        "Wheel of Fortune",
        "Mox Opal",
        "Lotus Petal",
        "Demonic Tutor",
        "Vampiric Tutor",
        "Imperial Seal",
        "Mystical Tutor",
        "Gamble",
        "Wishclaw Talisman",
        "Drannith Magistrate",
        "Opposition Agent",
        "Collector Ouphe",
        "Rule of Law",
        "Deafening Silence",
        "Dauthi Voidwalker",
        "Mana Crypt",
        "Jeweled Lotus",
        "Chain of Smog",
        "Voice of Victory",
        "Grand Abolisher",
        "Ranger-Captain of Eos",
        "Last Chance",
        "Silence",
        "Final Fortune",
        "Rhystic Study",
        "Smothering Tithe",
        "Mystic Remora",
        "City of Traitors",
        "Mishra's Workshop",
        "Ancient Tomb",
        "Gemstone Caverns",
        "Hexing Squelcher",
        "Lotho, Corrupt Shirriff",
        "Tataru Taru",
        "Valley Floodcaller",
        "Borne Upon a Wind",
        "Food Chain",
        "Eternal Scourge",
        "Misthollow Griffin",
        "Squee the Immortal",
        "Dualcaster Mage",
        "Twinflame",
        "Hoarding Broodlord",
        "Saw in Half",
        "Burnt Offering",
        "Sacrifice",
        "Culling the Weak",
    ]
    .iter()
    .map(|&s| super::crispi_model::normalize_card_name(s))
    .collect()
});
