use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct TwoCardComboDef {
    pub card_a: &'static str,
    pub card_b: &'static str,
    pub effects: &'static [&'static str],
    pub prereqs: u8,
}

pub static TWO_CARD_COMBOS: &[TwoCardComboDef] = &[
    TwoCardComboDef { card_a: "Demonic Consultation", card_b: "Thassa's Oracle", effects: &[], prereqs: 0 },
    TwoCardComboDef { card_a: "Exquisite Blood", card_b: "Sanguine Bond", effects: &["lifegain", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Tainted Pact", card_b: "Thassa's Oracle", effects: &[], prereqs: 1 },
    TwoCardComboDef { card_a: "Exquisite Blood", card_b: "Vito, Thorn of the Dusk Rose", effects: &["lifegain", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Dramatic Reversal", card_b: "Isochron Scepter", effects: &["mana"], prereqs: 1 },
    TwoCardComboDef { card_a: "Dualcaster Mage", card_b: "Twinflame", effects: &["ETB", "LTB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Bloodthirsty Conqueror", card_b: "Vito, Thorn of the Dusk Rose", effects: &["lifegain", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Niv-Mizzet, Parun", card_b: "Curiosity", effects: &["draw", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Gravecrawler", card_b: "Phyrexian Altar", effects: &["ETB", "LTB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Bloodthirsty Conqueror", card_b: "Sanguine Bond", effects: &["lifegain", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Chatterfang, Squirrel General", card_b: "Pitiless Plunderer", effects: &["mana", "LTB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Exquisite Blood", card_b: "Enduring Tenacity", effects: &["lifegain", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Bloodchief Ascension", card_b: "Mindcrank", effects: &["mill", "lifegain"], prereqs: 1 },
    TwoCardComboDef { card_a: "Basalt Monolith", card_b: "Forsaken Monument", effects: &["mana"], prereqs: 0 },
    TwoCardComboDef { card_a: "Exquisite Blood", card_b: "Marauding Blight-Priest", effects: &["lifegain", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Peregrin Took", card_b: "Nuka-Cola Vending Machine", effects: &["draw", "mana"], prereqs: 1 },
    TwoCardComboDef { card_a: "Dualcaster Mage", card_b: "Molten Duplication", effects: &["ETB", "LTB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Bruvac the Grandiloquent", card_b: "Maddening Cacophony", effects: &["mill"], prereqs: 0 },
    TwoCardComboDef { card_a: "Rings of Brighthearth", card_b: "Basalt Monolith", effects: &["mana"], prereqs: 0 },
    TwoCardComboDef { card_a: "Felidar Guardian", card_b: "Restoration Angel", effects: &["ETB", "LTB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Walking Ballista", card_b: "Heliod, Sun-Crowned", effects: &["damage", "lifegain"], prereqs: 1 },
    TwoCardComboDef { card_a: "Peregrine Drake", card_b: "Deadeye Navigator", effects: &["ETB", "LTB"], prereqs: 1 },
    TwoCardComboDef { card_a: "The Reaver Cleaver", card_b: "Aggravated Assault", effects: &["mana", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Niv-Mizzet, Parun", card_b: "Ophidian Eye", effects: &["draw", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Bloodthirsty Conqueror", card_b: "Marauding Blight-Priest", effects: &["lifegain", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Squee, the Immortal", card_b: "Food Chain", effects: &["mana", "ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Blasphemous Act", card_b: "Repercussion", effects: &["damage"], prereqs: 0 },
    TwoCardComboDef { card_a: "Niv-Mizzet, Parun", card_b: "Tandem Lookout", effects: &["draw", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Peregrin Took", card_b: "Experimental Confectioner", effects: &["draw"], prereqs: 1 },
    TwoCardComboDef { card_a: "Staff of Domination", card_b: "Priest of Titania", effects: &["draw", "mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Sword of Feast and Famine", card_b: "Aggravated Assault", effects: &["mana"], prereqs: 1 },
    TwoCardComboDef { card_a: "Blowfly Infestation", card_b: "Nest of Scarabs", effects: &["ETB", "LTB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Dualcaster Mage", card_b: "Saw in Half", effects: &["ETB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Zealous Conscripts", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Staff of Domination", card_b: "Elvish Archdruid", effects: &["draw", "mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Staff of Domination", card_b: "Marwyn, the Nurturer", effects: &["draw", "mana"], prereqs: 1 },
    TwoCardComboDef { card_a: "Dualcaster Mage", card_b: "Heat Shimmer", effects: &["ETB", "LTB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Niv-Mizzet, the Firemind", card_b: "Curiosity", effects: &["draw", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Ashaya, Soul of the Wild", card_b: "Quirion Ranger", effects: &["ETB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Scurry Oak", card_b: "Ivy Lane Denizen", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Godo, Bandit Warlord", card_b: "Helm of the Host", effects: &["ETB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Blowfly Infestation", card_b: "Hapatra, Vizier of Poisons", effects: &["ETB", "LTB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Basalt Monolith", card_b: "Zirda, the Dawnwaker", effects: &["mana"], prereqs: 0 },
    TwoCardComboDef { card_a: "Staff of Domination", card_b: "Karametra's Aide", effects: &["draw", "mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Niv-Mizzet, the Firemind", card_b: "Ophidian Eye", effects: &["draw", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Niv-Mizzet, the Firemind", card_b: "Tandem Lookout", effects: &["draw", "damage"], prereqs: 1 },
    TwoCardComboDef { card_a: "Vizier of Remedies", card_b: "Devoted Druid", effects: &["mana"], prereqs: 0 },
    TwoCardComboDef { card_a: "Malcolm, Keen-Eyed Navigator", card_b: "Glint-Horn Buccaneer", effects: &["mana", "damage"], prereqs: 2 },
    TwoCardComboDef { card_a: "Heliod, Sun-Crowned", card_b: "Triskelion", effects: &["damage", "lifegain"], prereqs: 1 },
    TwoCardComboDef { card_a: "Aurelia, the Warleader", card_b: "Helm of the Host", effects: &["ETB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Pestermite", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Village Bell-Ringer", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Hyrax Tower Scout", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Felidar Guardian", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Restoration Angel", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Deceiver Exarch", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Kiki-Jiki, Mirror Breaker", card_b: "Corridor Monitor", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Worldgorger Dragon", card_b: "Animate Dead", effects: &["mana", "ETB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Worldgorger Dragon", card_b: "Dance of the Dead", effects: &["mana", "ETB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Worldgorger Dragon", card_b: "Necromancy", effects: &["mana", "ETB"], prereqs: 1 },
    TwoCardComboDef { card_a: "Underworld Breach", card_b: "Lion's Eye Diamond", effects: &["mana"], prereqs: 3 },
    TwoCardComboDef { card_a: "Underworld Breach", card_b: "Brain Freeze", effects: &["mill"], prereqs: 3 },
    TwoCardComboDef { card_a: "Hullbreaker Horror", card_b: "Sol Ring", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Hullbreaker Horror", card_b: "Mana Vault", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Hullbreaker Horror", card_b: "Mana Crypt", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Hullbreaker Horror", card_b: "Mox Amber", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Hullbreaker Horror", card_b: "Mox Opal", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Hullbreaker Horror", card_b: "Chrome Mox", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Sanguine Bond", card_b: "Exquisite Blood", effects: &["damage", "lifegain"], prereqs: 1 },
    TwoCardComboDef { card_a: "Vito, Thorn of the Dusk Rose", card_b: "Exquisite Blood", effects: &["damage", "lifegain"], prereqs: 1 },
    TwoCardComboDef { card_a: "Dina, Soul Steeper", card_b: "Exquisite Blood", effects: &["damage", "lifegain"], prereqs: 1 },
    TwoCardComboDef { card_a: "Vizier of Remedies", card_b: "Devoted Druid", effects: &["mana"], prereqs: 0 },
    TwoCardComboDef { card_a: "Swift Reconfiguration", card_b: "Devoted Druid", effects: &["mana"], prereqs: 0 },
    TwoCardComboDef { card_a: "Basalt Monolith", card_b: "Kinnan, Bonder Prodigy", effects: &["mana"], prereqs: 0 },
    TwoCardComboDef { card_a: "Selvala, Heart of the Wilds", card_b: "Umbral Mantle", effects: &["mana", "draw"], prereqs: 2 },
    TwoCardComboDef { card_a: "Marwyn, the Nurturer", card_b: "Umbral Mantle", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Elvish Archdruid", card_b: "Umbral Mantle", effects: &["mana"], prereqs: 3 },
    TwoCardComboDef { card_a: "Priest of Titania", card_b: "Umbral Mantle", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Karametra's Aide", card_b: "Umbral Mantle", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Circle of Dreams Druid", card_b: "Umbral Mantle", effects: &["mana"], prereqs: 3 },
    TwoCardComboDef { card_a: "Selvala, Heart of the Wilds", card_b: "Staff of Domination", effects: &["mana", "draw"], prereqs: 2 },
    TwoCardComboDef { card_a: "Marwyn, the Nurturer", card_b: "Staff of Domination", effects: &["mana", "draw"], prereqs: 2 },
    TwoCardComboDef { card_a: "Elvish Archdruid", card_b: "Staff of Domination", effects: &["mana", "draw"], prereqs: 3 },
    TwoCardComboDef { card_a: "Priest of Titania", card_b: "Staff of Domination", effects: &["mana", "draw"], prereqs: 2 },
    TwoCardComboDef { card_a: "Karametra's Aide", card_b: "Staff of Domination", effects: &["mana", "draw"], prereqs: 2 },
    TwoCardComboDef { card_a: "Circle of Dreams Druid", card_b: "Staff of Domination", effects: &["mana", "draw"], prereqs: 3 },
    TwoCardComboDef { card_a: "Selvala, Explorer Returned", card_b: "Umbral Mantle", effects: &["mana", "draw"], prereqs: 2 },
    TwoCardComboDef { card_a: "Selvala, Explorer Returned", card_b: "Staff of Domination", effects: &["mana", "draw"], prereqs: 2 },
    TwoCardComboDef { card_a: "Solphim, Mayhem Dominus", card_b: "Heartless Hidetsugu", effects: &["damage"], prereqs: 0 },
    TwoCardComboDef { card_a: "Eternal Scourge", card_b: "Food Chain", effects: &["mana", "ETB"], prereqs: 2 },
    TwoCardComboDef { card_a: "Chain of Smog", card_b: "Witherbloom Apprentice", effects: &["infinite life gain / life loss"], prereqs: 0 },
    TwoCardComboDef { card_a: "Staff of Domination", card_b: "Selvala, Heart of the Wilds", effects: &["draw", "mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Combat Celebrant", card_b: "Kiki-Jiki, Mirror Breaker", effects: &["ETB"], prereqs: 0 },
    TwoCardComboDef { card_a: "Umbral Mantle", card_b: "Elvish Archdruid", effects: &["mana"], prereqs: 3 },
    TwoCardComboDef { card_a: "Abdel Adrian, Gorion's Ward", card_b: "Animate Dead", effects: &["ETB"], prereqs: 5 },
    TwoCardComboDef { card_a: "Umbral Mantle", card_b: "Marwyn, the Nurturer", effects: &["mana"], prereqs: 2 },
    TwoCardComboDef { card_a: "Cultivator Colossus", card_b: "Abundance", effects: &["Play all lands from deck", "Infinite Landfall"], prereqs: 1},

];


#[derive(Debug, Clone, Serialize)]
pub struct ThreeCardComboDef {
    pub card_a: &'static str,
    pub card_b: &'static str,
    pub card_c: &'static str,
    pub effects: &'static [&'static str],
    pub prereqs: u8,
}

pub static THREE_CARD_COMBOS: &[ThreeCardComboDef] = &[
    ThreeCardComboDef { card_a: "Underworld Breach", card_b: "Lion's Eye Diamond", card_c: "Brain Freeze", effects: &["infinite mill"], prereqs: 2},
    ThreeCardComboDef { card_a: "Underworld Breach", card_b: "Grinding Station", card_c: "Paradise Mantle", effects: &["infinite self mill"], prereqs: 2},
    ThreeCardComboDef { card_a: "Saw in Half", card_b: "Hoarding Broodlord", card_c: "Sacrifice", effects: &["Free Double Tutor/Cast"], prereqs: 2},
    ThreeCardComboDef { card_a: "Saw in Half", card_b: "Hoarding Broodlord", card_c: "Burnt Offering", effects: &["Free Double Tutor/Cast"], prereqs: 2},
    ThreeCardComboDef { card_a: "Saw in Half", card_b: "Hoarding Broodlord", card_c: "Culling the Weak", effects: &["Free Double Tutor/Cast"], prereqs: 3},
];
